<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "estadistica_unal_new"
 *
 * Auto generated by Extension Builder 2020-02-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Estadistica Unal 2.0',
    'description' => 'Nueva version de la extensión estadisticas unal',
    'category' => 'plugin',
    'author' => 'Alexis Ortiz, Alexis Ortiz ft. Camilo Neiva',
    'author_email' => 'eaortiz@unal.edu.co, jcneivaa@unal.edu.co ',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
